---
# tasks file for terraform_script

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: present

- name: creating a folder 
  ansible.builtin.file:
    path: /tmp/terraform_file
    mode: "0755" 
    state: directory

- name: Copy Terraform script
  ansible.builtin.copy:
    src: main.tf
    dest: /tmp/terraform_file/main.tf

- name: Copy Terraform script
  ansible.builtin.copy:
    src: variables.tf
    dest: /tmp/terraform_file/variables.tf

- name: Initialize Terraform
  ansible.builtin.command:
    cmd: terraform init
    chdir: /tmp/terraform_file

- name: Apply Terraform script
  ansible.builtin.command:
    cmd: terraform apply -auto-approve
    chdir: /tmp/terraform_file

